#!/bin/bash
#
# A helper script which would merge/push afni source for test build on travis

cd /home/neurodebian/git/afni-testing
git checkout testing
git fetch origin
git fetch gh-yarikoptic
git merge -m "automated merge of custom testing changes" gh-yarikoptic/testing
git merge -m "automated merge of fresh upstream" origin/master
git push gh-yarikoptic testing
echo "Pushed for testing"
